// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAoM---V1gE5W0dLeHJaZFbJLrPPI0js',
    appId: '1:639457447534:web:d00e8bff7bc78b41f3607f',
    messagingSenderId: '639457447534',
    projectId: 'reddit-clone-yashxcodes',
    authDomain: 'reddit-clone-yashxcodes.firebaseapp.com',
    storageBucket: 'reddit-clone-yashxcodes.appspot.com',
    measurementId: 'G-ZDKDQJP5HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc14RkLMjY6NVQH9Mf_qRLFYfqwby6Mcg',
    appId: '1:639457447534:android:d090722a7b7ad1b1f3607f',
    messagingSenderId: '639457447534',
    projectId: 'reddit-clone-yashxcodes',
    storageBucket: 'reddit-clone-yashxcodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0jlNy07lg4rCxDQ4dvI5zmwTXNUebKk',
    appId: '1:639457447534:ios:62f9eaeeb59a9403f3607f',
    messagingSenderId: '639457447534',
    projectId: 'reddit-clone-yashxcodes',
    storageBucket: 'reddit-clone-yashxcodes.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
